### ISSUE TITLE
Import duration from Alexa timers

### ISSUE THREAD

**Issue by hyukishi** [sopelj/lovelace-timer-card#1]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I would like to utilize this timer card with timers started in Alexa. It should pull the duration of the timer from Alexa and when the state returns "unavailable" it should clear the timer as if to say the timer is not set. This would use the Alexa Media Player integration that is already publicly available. As it stands now, the timer can not be set/started/cleared by using Alexa voice commands.

**Describe alternatives you've considered**

**Additional context**

**Comment by sopelj** [comment]
Hey, I'm really sorry. I didn't see this. I'll enable email notifications for future issues.

I don't have an Alexa, so I can't really test, but what sort of entity does it create in Home Assistant for these timers?
I don't know if [this is the integration](https://github.com/custom-components/alexa_media_player/wiki#notifications) to which are referring, but if it is, it seems to give the time at which the next timer starts and not its duration.

**Comment by hyukishi** [comment]
That’s the integration. It uses the next timer entity to find the start and end times, but it doesn’t do accurate math down to the second when the timer is longer than 1 minute. I was drawn to your custom card because of the possibility of seeing that data down to the second regardless of the timer length.

Currently, if you use an entity card and set it for the next timer entity you see something like “In 20 minutes.” As opposed to a format of HH:MM:SS.

**Comment by sopelj** [comment]
Oh ok, so it should contain the time at which the next timer ends? And the desired result it to show a countdown between now and that date?

Do you think you could possible show me an example of your `sensor.media_player_next_timer` in Developer Tools -> States ? I need to know what attributes it contains as they clearly aren't the same as a timer. 

Thanks

**Comment by hyukishi** [comment]
The below info is from a 15-minute timer set on the echo dot in my office space.

Entity: `sensor.guest_bedroom_echo_dot_next_timer`
State: `2021-03-08T08:18:53-06:00`
Attributes:
```recurrence: Never Repeat
process_timestamp: '2021-03-08T08:03:56.186939-06:00'
prior_value: '2021-03-08T08:18:54-06:00'
total_active: 1
total_all: 1
sorted_active: >-
  [["61d5573e-c7b3-3498-a77d-6067c63816c4", {"alarmTime": 0, "assigner": null,
  "automationId": null, "createdDate": 1615212233574, "deferredAtTime": null,
  "deliveryType": null, "deviceName": null, "deviceSerialNumber":
  "XXXXXXXXXXXXXX", "deviceType": "A3S5BH2HU6VAYF", "extensibleAttribute":
  null, "geoLocationTriggerData": null, "id":
  "XXXXXXXXXXXXXX",
  "lastOccurrenceTimeInMilli": 0, "lastUpdatedDate": 0, "loopCount": null,
  "mrmGroupContext": null, "musicAlarmId": null, "musicEntity": null,
  "notificationIndex": "61d5573e-c7b3-3498-a77d-6067c63816c4", "originalDate":
  null, "originalTime": null, "personProfile": null, "provider": null,
  "rRuleData": null, "recurrenceEligibility": false, "recurringPattern": null,
  "remainingTime": 897000.0, "reminderAppLabel": null, "reminderLabel": null,
  "reminderSubLabel": null, "skillInfo": null, "snoozedToTime": null, "sound":
  {"displayName": "Simple Timer", "folder": null, "id":
  "system_alerts_melodic_02", "isChildDirected": false, "numAssets": 0,
  "pricing": null, "providerId": "ECHO", "sampleUrl":
  "https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_02.mp3"},
  "status": "ON", "targetPersonProfiles": null, "timeZoneId": null,
  "timerLabel": null, "tmwNotificationProperties": null, "triggerTime":
  1615213133559, "type": "Timer", "version": "3"}]]
sorted_all: >-
  [["61d5573e-c7b3-3498-a77d-6067c63816c4", {"alarmTime": 0, "assigner": null,
  "automationId": null, "createdDate": 1615212233574, "deferredAtTime": null,
  "deliveryType": null, "deviceName": null, "deviceSerialNumber":
  "G090LF11751407TL", "deviceType": "A3S5BH2HU6VAYF", "extensibleAttribute":
  null, "geoLocationTriggerData": null, "id":
  "A3S5BH2HU6VAYF-G090LF11751407TL-61d5573e-c7b3-3498-a77d-6067c63816c4",
  "lastOccurrenceTimeInMilli": 0, "lastUpdatedDate": 0, "loopCount": null,
  "mrmGroupContext": null, "musicAlarmId": null, "musicEntity": null,
  "notificationIndex": "61d5573e-c7b3-3498-a77d-6067c63816c4", "originalDate":
  null, "originalTime": null, "personProfile": null, "provider": null,
  "rRuleData": null, "recurrenceEligibility": false, "recurringPattern": null,
  "remainingTime": 897000.0, "reminderAppLabel": null, "reminderLabel": null,
  "reminderSubLabel": null, "skillInfo": null, "snoozedToTime": null, "sound":
  {"displayName": "Simple Timer", "folder": null, "id":
  "system_alerts_melodic_02", "isChildDirected": false, "numAssets": 0,
  "pricing": null, "providerId": "ECHO", "sampleUrl":
  "https://s3.amazonaws.com/deeappservice.prod.notificationtones/system_alerts_melodic_02.mp3"},
  "status": "ON", "targetPersonProfiles": null, "timeZoneId": null,
  "timerLabel": null, "tmwNotificationProperties": null, "triggerTime":
  1615213133559, "type": "Timer", "version": "3"}]]
friendly_name: Guest Bedroom Echo Dot next Timer
icon: 'mdi:timer-outline'
device_class: timestamp
```

**Comment by sopelj** [comment]
Hey, sorry it took so long. 
I finally got to updating the module to work with Google Home timers and I tried to add support for Alexa Media Player based on your example. 
If you update to the version 0.2.0 in theory it should work with your example, but the values might be a bit off or come out weird. If you test it and find any issues I'd be happy to fix them, but it's really hard to test without a working example. 
If you do test it and it works or not please let me know. Thanks!

**Comment by hyukishi** [comment]
I just tried it out and unfortunately I cannot add sensor type devices. They have to be timers. If you could add the ability to use sensor entities I can give it another go and let you know.

**Comment by sopelj** [comment]
Really? It's called `sensor.[the name]_next_timer` right? If not you can always switch to yaml mode in the editor and you'll be able to add it. It's just filtered for convenience.

**Comment by hyukishi** [comment]
I added the entity in yaml mode but it did not produce any sort of output on the card.

Here’s my state info for a 5 minute timer.

recurrence: Never Repeat
process_timestamp: '2021-04-21T20:30:20.247072-05:00'
prior_value: '2021-04-21T20:35:19-05:00'
total_active: 1
total_all: 2

I’m leaving off the sorted_active information because it contains sensitive info. Hopefully the info provided above is sufficient.

**Comment by sopelj** [comment]
Oh thank you! I'm actually using the `createdDate`, `remainingTime` and `triggerTime` in the list of timers as this allows for listing all running timers instead of just the next. At least that's the theory and that's what it does for Google. 
I think I was accessing the list incorrectly. I changed it and made a new release (0.2.1) I hope that works if not I'll see if I can fix it tomorrow after work. Thanks for your help. :)

**Comment by hyukishi** [comment]
I tried again with the updated card just a moment ago and I still see no output on it. Also worth mentioning is that I set the entity in yaml mode, but when I go back to visual mode the entity field is empty. I’m not sure if that has something to do with it or not.

**Comment by sopelj** [comment]
Indeed, it wasn't working. I had to actually setup and Alexa Dot and the integration to figure out what was wrong. I think I've finally got it working though!

Sometimes it seems to be off by a couple seconds. It might be a difference between the browser and the device. I'll do some more testing, but it should load correctly for you now as of v0.2.2.

Are you sure your sensors don't appear in the editor entity list though? I see them in mine. Perhaps if you clear your cache?

![Screenshot_20210422_210025](https://user-images.githubusercontent.com/5285941/115803631-4492ae80-a3af-11eb-9f15-23de8c6029ad.png)

**Comment by hyukishi** [comment]
Seems to be working all the way around now. Sensors show up in the entity dropdown menu and the timer counts down from about the time (give or take 2 seconds) that the timer is set for on the device.

Thank you for your persistence in implementing this fix!

**Comment by sopelj** [comment]
That's awesome! I'll look into the delay, but I think that's something that affects all the types of timers so might be a separate issue. So I think  I'll close this issue but feel free to open other issues if you find something. No problem!  Thanks for your help!
