### ISSUE TITLE
Card name not appearing after being added initially

### ISSUE THREAD

**Issue by hyukishi** [sopelj/lovelace-timer-card#2]
**Release with the issue:**
2.0.2
**Last working release (if known):**
N/A
**Browser and Operating System:**
Firefox on MacOS Big Sur

**Description of problem:**
The timer's name when assigned during card creation is hidden when the timer is running. After the timer is stopped, the name also does not re-appear.
![image](https://user-images.githubusercontent.com/11379349/115879151-f614fc80-a40e-11eb-9379-f67962b31b60.png)
![image](https://user-images.githubusercontent.com/11379349/115879201-04fbaf00-a40f-11eb-9fc3-51c783fd2bf8.png)

**Comment by sopelj** [comment]
Hey, sorry I missed it. This should be fixed in 0.2.3

**Comment by sopelj** [comment]
I tested it and seems to work. So I'll close the issue, but if have any issues don't hesitate to comment.

**Comment by hyukishi** [comment]
I apologize for the late response. I can verify that the card is working as it should now. I did notice that the difference in the last few seconds of the timer was exactly 2 seconds extra on the timer created by your card versus the entity card countdown in HA. So you should be able to subtract 2 seconds initially from the card's config or potentially add an offset value that users can modify in the card config to suit their needs as it may not be the exact same for everyone.

**Comment by sopelj** [comment]
No worries! Thanks for the follow-up!
That's the Alexa timer or all types of timers? I did notice my tests on Alexa were off ｂｙ exactly two seconds as well. That's probably the norm then. I'll start with subtracting the two seconds and keep an eye on it. If it fluctuates I'll add a setting.

**Comment by hyukishi** [comment]
Yep it was just the Alexa timers. Good deal sir.
